name: Run Tests and Send Coverage to Codecov

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r linter-requirements.txt
        pip install -r docs-requirements.txt
        pip install -r aws-lambda-layer-requirements.txt
        pip install -r test-requirements.txt
        pip install coverage
        pip install pytest
        pip install Flask
        pip install pytest-django
        pip install fakeredis
    - name: Run Tests with Coverage
      run: |
        coverage run -m --branch pytest tests
        coverage xml -o coverage.xml
      continue-on-error: true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
            

